name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopy=2.3.0=pyhd8ed1ab_0
  - matplotlib=3.7.0=py310haa95532_0
  - matplotlib-base=3.7.0=py310h4ed8f06_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - numpy=1.23.5=py310h60c9a35_0
  - numpy-base=1.23.5=py310h04254f7_0
  - numpydoc=1.5.0=py310haa95532_0
  - pandas=1.5.3=py310h4ed8f06_0
  - seaborn=0.12.2=py310haa95532_0
  - streamlit=1.22.0=pyhd8ed1ab_2
  - pip:
      - click-plugins==1.1.1
      - cligj==0.7.2
      - fiona==1.9.3
      - geojson==3.0.1
      - geopandas==0.12.2
      - keplergl==0.3.2
      - munch==2.5.0
      - osmnx==1.3.0
      - pylint-venv==2.3.0
      - pyproj==3.5.0
      - qstylizer==0.2.2
      - qtawesome==1.2.2
      - qtconsole==5.4.0
      - shapely==2.0.1
      - streamlit-keplergl==0.3.0
      - traittypes==0.2.1
